server:
  port: 80
spring:
  mvc:
    view:
      suffix: html
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/oboiservice?createDatabaseIfNotExist=true
    username: root
    password: mysql.server


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

